// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Nastice.GoogleAuthenticateLab.Data.Nastice.GoogleAuthenticateLab.Data.DTOs;

public partial class User
{
    /// <summary>
    /// 流水號
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string Account { get; set; } = null!;

    /// <summary>
    /// 密碼
    /// </summary>
    public string Password { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string Email { get; set; } = null!;

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool Enable { get; set; }

    /// <summary>
    /// 密鑰
    /// </summary>
    public string? Secret { get; set; }

    /// <summary>
    /// 備份碼
    /// </summary>
    public string? BackupCodes { get; set; }

    /// <summary>
    /// 最後一次登入時間
    /// </summary>
    public DateTime? LastLogonAt { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }
}