// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Nastice.GoogleAuthenticateLab.Data.Nastice.GoogleAuthenticateLab.Data.DTOs;

namespace Nastice.GoogleAuthenticateLab.Data.Nastice.GoogleAuthenticateLab.Data.DAOs;

public partial class MssqlContext : DbContext
{
    public MssqlContext(DbContextOptions<MssqlContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pk");

            entity.ToTable("users");

            entity.Property(e => e.Id)
                .HasComment("流水號")
                .HasColumnName("id");
            entity.Property(e => e.Account)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("帳號")
                .HasColumnName("account");
            entity.Property(e => e.BackupCodes)
                .HasMaxLength(1024)
                .IsUnicode(false)
                .HasComment("備份碼")
                .HasColumnName("backup_codes");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("建立時間")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(320)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Enable)
                .HasDefaultValue(true)
                .HasComment("是否啟用")
                .HasColumnName("enable");
            entity.Property(e => e.LastLogonAt)
                .HasComment("最後一次登入時間")
                .HasColumnName("last_logon_at");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("密碼")
                .HasColumnName("password");
            entity.Property(e => e.Secret)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasComment("密鑰")
                .HasColumnName("secret");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}